#!/usr/bin/env bash

set -e

source .config

lpass login "$lastpass_username"

if ! ps -p "$SSH_AGENT_PID" > /dev/null; then
    eval "$(ssh-agent -s)"
fi
unique_names=$(lpass ls --color=never $lastpass_sshgroup | cut -d ' ' -f1)

for unique_name in $unique_names; do
    private_key=$(lpass show --field="Private Key" "$unique_name")
    SSH_ASKPASS_FOR=$unique_name DISPLAY=":0.0" SSH_ASKPASS="$PWD/ssh_askpass.sh" nohup ssh-add - <<< "${private_key}"
done
